name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ stable, 2.13.4, dev ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v0.2
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Formatting
        run: dart format --output=none --set-exit-if-changed .
        if: always() && ${{ matrix.sdk }} == 'stable'

      - name: Analysis
        run: dart analyze

      - name: Tests
        run: dart test
        if: ${{ matrix.sdk == '2.13.4' }}
