name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.18.7, 2.19.6 ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Formatting
        run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk }} == '2.18.7'

      - name: Analysis
        run: dart analyze

      - name: Tests
        run: dart test --chain-stack-traces

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json

